#!/bin/sh

IPV4=192.0.2.1
IPV6=2001:db8:ffff:a000:fdc0::3b5

PORT=18120
PASS=foobar

add () {
	[ "$IPV4" ] && [ -z "$(ip addr show dev lo scope global | grep " inet ${IPV4}/32 ")" ] \
			&& ip addr add ${IPV4}/32 dev lo
	[ "$IPV6" ] && [ -z "$(ip addr show dev lo scope global | grep " inet6 ${IPV6}/128 ")" ] \
			&& ip addr add ${IPV6}/128 dev lo

	return 0
}

del () {
	[ "$IPV4" ] && [ -n "$(ip addr show dev lo scope global | grep " inet ${IPV4}/32 ")" ] \
			&& ip addr del ${IPV4}/32 dev lo
	[ "$IPV6" ] && [ -n "$(ip addr show dev lo scope global | grep " inet6 ${IPV6}/128 ")" ] \
			&& ip addr del ${IPV6}/128 dev lo

	return 0
}

stop () {
	del

	kill -STOP $(pgrep -f $SELF)
}

quit () {
	del

	exit 0
}

check () {
	# we only test the IPv4 side
	echo "Message-Authenticator = ''" | radclient -q -t 1.0 -r 1 127.0.0.1:$PORT status $PASS

	[ $? -eq 0 ] && add || del
}

go () {
	trap quit TERM
	trap stop TSTP

	while true; do
		check

		sleep 1
	done
}

SELF=$(basename "$0")
PROCS=$(pgrep -f "^/bin/sh $0\$")
RC=$?
if [ $RC -gt 0 ]; then
	echo "unexpected pgrep results (ret=$RC)" > /dev/stderr
	exit 70
fi
if [ "$PROCS" != "$$" ]; then
	echo "'$SELF' is already running" > /dev/stderr
	exit 69
fi

0<&- 1<&- 2<&- go &

exit 0
